// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace eforsah_v1
{
	public partial class SubCategoryViewController : UINavigationController
	{
		public SubCategoryViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
